name: Build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '16'
    
    - run: ant -f ${{github.workspace}} -Dnb.internal.action.name=build jar
    - shell: cmd
      working-directory: dist
      run: 7z a ${{github.workspace}}\\Whitehole-Neo.zip *.* -r
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: auto
        name: Whitehole-Neo Auto Build
        prerelease: true
        files: Whitehole-Neo.zip