name: Build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '11'
    
    -  shell: cmd
       run: ant -Dnb.internal.action.name=build jar
    - shell: cmd
      working-directory: dist
      run: 7z a ${{github.workspace}}\\Whitehole-Neo.zip *.* -r
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: |
          ${{github.workspace}}/dist
          ${{github.workspace}}/lib